name: CI

on:
  push:
    branches:
      - master

jobs:
  checkout-and-test:
    name: "Checkout and Test"
    runs-on: ubuntu-latest

    steps:
      # Análise do projeto
      - name: Checkout
        uses: actions/checkout@v4

      # Teste do projeto
      - name: Test
        run: node --test index.test.js
